apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-storage
spec:
  serviceName: "my-service"
  updateStrategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/icai2025-456716/storage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: my-storage
              mountPath: /data/storage/
  volumeClaimTemplates:
    - metadata:
        name: my-storage
      spec:
        storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
# Sé que hay que crear el disco, pero luego no sé atachearlo. Porque a lo mejor podría usar el que está en el cluster,
# pero es que no sé referenciarlo
# apiVersion: v1
# kind: StorageClass
# metadata:
#   - name: emptydir
# spec:
#   storageClassName: emptydir
#   accessModes: ["ReadWriteOnce"]
#   resources:
#     requests:
#       storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: my-storage
spec:
  clusterIP: my-service
  selector:
    app: web
  ports:
    - port: 3000
