apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-storage
spec:
  serviceName: "my-service"
  updateStrategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: my-container
          image: gcr.io/icai2025-456716/storage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: GKEVolume
              mountPath: /var/storage/
  volumeClaimTemplates:
    - metadata:
        name: storage-volume
      spec:
        storageClassName: GKEVolume
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: storage
spec:
  clusterIP: 34.118.224.0
  selector:
    app: python-app
  ports:
    - port: 3000
