apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: gcr.io/icai2025-456716/web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: STORAGE_SVC
              value: "my-storage"
          livenessProbe:
            httpGet:
              path: /probe
              port: 3000
            periodSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: 10.11.241.93

spec:
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer